In [5]:
import pandas as pd
import numpy as np

pd.read_csv('../LAUNCH_1.TXT', delimiter='\t', header=None)

        0     1     2     3     4     5      6      7
0    0.98  0.13  0.08  0.11 -1119  6003 -11259     16
1    0.98  0.12  0.08  0.11 -1756  7619 -10625     53
2    0.99  0.10  0.05  0.09 -2179  8303  -8867     84
3    0.99  0.07  0.02  0.07 -2284  7777  -6116    114
4    1.00  0.05 -0.02  0.05 -1692  6364  -3089    145
..    ...   ...   ...   ...   ...   ...    ...    ...
963  1.00  0.08  0.00 -0.01    -3    39    166  29910
964  1.00  0.08  0.00 -0.01    -4    35    166  29942
965  1.00  0.08  0.00 -0.01    -6    36    165  29975
966  1.00  0.08  0.00 -0.01    -3    30    165  30008
967  1.00  0.08  0.00 -0.01    -3    30    165  34055

[968 rows x 8 columns]